### ISSUE TITLE
Error when launching Floppy : managedNodes.dat not found

### ISSUE THREAD

**Issue by rbarzic** [JLuebben/Floppy#28]
Hello,

I have the following error when trying to launch the Floppy.py program under bin.

roba@roba-OptiPlex-7010:~/perso/github/Floppy/bin (master)*
13:23:48:$ python3 Floppy.py 
Warning: error in custom node:
No module named 'lauescript'
Warning: error in custom node:
No module named 'lauescript'
Traceback (most recent call last):
  File "Floppy.py", line 4, in <module>
    floppy.main.run()
  File "/home/roba/perso/github/Floppy/floppy/main.py", line 22, in run
    startUI(app, painter)
  File "/home/roba/perso/github/Floppy/floppy/main.py", line 33, in startUI
    win = MainWindow(painter=painter)
  File "/home/roba/perso/github/Floppy/floppy/floppyUi.py", line 1801, in __init__
    NodeWizardDialog.loadManagedNodes()
  File "/home/roba/perso/github/Floppy/floppy/floppyUi.py", line 1747, in loadManagedNodes
    with open(filePath, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/home/roba/perso/github/Floppy/floppy/CustomNodes/managedNodes.dat'

Is there something I'm doing wrong ?

**Comment by uroboro** [comment]
Create an empty file at that location with:

`touch ~/perso/github/Floppy/floppy/CustomNodes/managedNodes.dat`

**Comment by Mister-Lemon** [comment]
Thanks @uroboro, I also encountered this issue and it solved it.
