### ISSUE TITLE
[run] examples and tests

### ISSUE THREAD

**Issue by neodark** [JLuebben/Floppy#29]
Hello,

this project seems quite interesting. However, I am unable to launch the test or run the examples.

Could you give me an insight on which dependencies are required (requirements.txt) and how to launch the examples and launch the tests etc. please?

Thanks in advance for your answer.

**Comment by Mister-Lemon** [comment]
same here. following.

**Comment by ef-ex** [comment]
Yes me too, everytime i try to run it i get this 


Warning: error in custom node:
No module named 'lauescript'
Warning: error in custom node:
No module named 'lauescript'
Traceback (most recent call last):
  File "G:\script\NodeEditor\nodeEditor.py", line 5, in <module>
    main.run()
  File "g:/script/NodeEditor/floppy\floppy\main.py", line 22, in run
    startUI(app, painter)
  File "g:/script/NodeEditor/floppy\floppy\main.py", line 33, in startUI
    win = MainWindow(painter=painter)
  File "g:/script/NodeEditor/floppy\floppy\floppyUi.py", line 1801, in __init__
    NodeWizardDialog.loadManagedNodes()
  File "g:/script/NodeEditor/floppy\floppy\floppyUi.py", line 1747, in loadManagedNodes
    with open(filePath, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'g:/script/NodeEditor/floppy\\floppy\\CustomNodes\\managedNodes.dat'

**Comment by numan98khan** [comment]
for the lauescript module check this link out:
https://github.com/JLuebben/Laue-Script/blob/master/installGuide.txt

**Comment by LinuxerAlan** [comment]
Following as well. I could define the class and func, but how to use (run) it?
